package com.emi.tui.modules;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import lombok.Data;

//single shared object passes through all the sreens 
//each screen fills the relevant data 
//passes the same instance to next screen, so the data is shared across all screens and can be used to make decisions on what to show and what not to show


/* flow - 

   MetaDataScreen     → fills group, artifact, name, javaVersion, buildTool, bootVersion
   DependencyScreen   → fills dependencies
   OutputDirScreen    → fills outputDirectory, projectEnvironment
   GeneratingScreen   → uses everything above to call InitializrClient + ZipExtractor
   IdeSelectionScreen → fills chosenIde
*/

@Data
public class ProjectConfig {
  

  //metadata screen

  private String artifactId  = "demo" ; 

  private String groupId     = "com.example" ;

  private String name        = "demo" ;

  private String javaVersion = "17" ;

  private String buildTool   = "MAVEN" ;

  private String bootVersion = "2.7.5" ;

  private String packaging   = "JAR" ;

  private String description   = "Demo project generated by Terminal User Interface" ;


  //dependency screen

  List<String> dependencies = new ArrayList<>();

  //output dir screen

  private String outputDirectory = System.getProperty("user.home") +  File.separator + "projects";;

  private Environment projectEnvironment ;

 //ide selection screen

  private DetectedIde chosenIde ;


  //Derived helpers — used by InitializrClient to build the URL

  public String dependenciesAsStrings(){
        return String.join(",", dependencies);
  }

  public String resolvedProjectPath() {
    String separator = outputDirectory.contains("\\") ? "\\" : "/";
    return outputDirectory + separator + artifactId;
  }


    public String validate() {
      if (groupId == null || groupId.isBlank())
          return "Group ID cannot be empty";
      if (artifactId == null || artifactId.isBlank())
          return "Artifact ID cannot be empty";
      if (!artifactId.matches("[a-z0-9\\-]+"))
          return "Artifact ID must be lowercase letters, numbers, or hyphens";
      if (outputDirectory == null || outputDirectory.isBlank())
          return "Output directory cannot be empty";
      return null; // valid
    }
}
